name: Release

on:
  push:
    tags:
      - v*.*.*


jobs:
  image:
    name: Build App Image
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Set IMAGE_TAG env
        run: echo "IMAGE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_SYSTEM_REPOSITORY_ACCOUNT }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            asia-northeast1-docker.pkg.dev/cpctf-338715/system/ssh-separator:${{env.IMAGE_TAG}}
            asia-northeast1-docker.pkg.dev/cpctf-338715/system/ssh-separator:latest


